package webTest;// Generated by Selenium IDE

import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.edge.EdgeDriver;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class ComprarPassagemSIDE {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeEach
    public void setUp() {
        //        ChromeOptions options = new ChormeOptions();
        //        options.addArguments("--remote-allow-origins=*");

        //Aponta onde está o Chorme Driver:
        //        System.setProperty("webdriver.chrome.driver", "drivers/chrome/chromedriver.exe");
        //        driver = new ChromeDriver(options);
        //        js = (JavascriptExecutor) driver;
        //        vars = new HashMap<String, Object>();

        // Defina o caminho do Edge WebDriver
        System.setProperty("webdriver.edge.driver", "drivers/edge/msedgedriver.exe"); // Aponta onde está o Edge

        // Inicia o EdgeDriver
        driver = new EdgeDriver(); // Inicia

        // Inicializa o JavascriptExecutor
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();

    }
    @AfterEach
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void comprarPassagem() {
        driver.get("https://blazedemo.com/");
        driver.manage().window().setSize(new Dimension(1295, 688));
        driver.findElement(By.cssSelector(".btn-primary")).click();
        driver.findElement(By.cssSelector("tr:nth-child(1) .btn")).click();
        driver.findElement(By.id("rememberMe")).click();
        driver.findElement(By.id("inputName")).click();
        driver.findElement(By.id("inputName")).sendKeys("Ivan Junio Medeiros Ferreira");
        driver.findElement(By.id("address")).sendKeys("Quadra 55, casa 1");
        driver.findElement(By.id("city")).sendKeys("Aguas Lindas");
        driver.findElement(By.id("state")).sendKeys("Goiás");
        driver.findElement(By.id("zipCode")).sendKeys("72911316");
        driver.findElement(By.cssSelector("body")).click();
        driver.findElement(By.id("zipCode")).sendKeys("0000000");
        driver.findElement(By.cssSelector("em")).click();
        driver.findElement(By.cssSelector("em")).click();
        assertThat(driver.findElement(By.cssSelector("em")).getText(), is("914.76"));
        driver.findElement(By.cssSelector(".btn-primary")).click();
        driver.findElement(By.cssSelector("h1")).click();
        driver.findElement(By.cssSelector("h1")).click();
        driver.findElement(By.cssSelector("h1")).click();
        assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Thank you for your purchase today!"));
    }
}
